### ISSUE TITLE
Funcionabilidade do pacote em diferentes versões do Python

### ISSUE THREAD

**Issue by BrunoRiibeiro** [fga-eps-mds/2022-2-ez-docs#74]
# Descrição

Verificar e testar em quais versões do Python o pacote funiona, fazer o teste desde o Python 2.0.1 até a versão mais nova Python 3.11.1, sendo pelo menos 10 casos testes.

## Critérios de avaliação

- [x] 10 casos testes, 1 por versão
- [x] Funcionamento normal de todo, relaçao dos erros encontrados
- [x]  Atualização do README
- [x] branch e pull request

**Comment by BrunoRiibeiro** [comment]
Concluído, será mantido, por hora, apenas em Python3
